name: Auto Update Vacancy Status

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
        env:
          GSPREAD_JSON: ${{ secrets.GSPREAD_JSON }}
          ES_EMAIL: ${{ secrets.ES_EMAIL }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

      - name: Upload screenshots
        if: always()  # 成功・失敗問わず必ず実行
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
